formatting:
  active: true
  MaximumLineLength:
    active: false
  TrailingCommaOnCallSite:
    active: true
    useTrailingCommaOnCallSite: true
  TrailingCommaOnDeclarationSite:
    active: true
    useTrailingCommaOnDeclarationSite: true
  NoWildcardImports:
    active: false

complexity:
  active: true
  TooManyFunctions:
    active: true
    thresholdInFiles: 20
    thresholdInClasses: 20
    thresholdInInterfaces: 20
    thresholdInObjects: 20
    thresholdInEnums: 20
    ignoreDeprecated: true
    ignorePrivate: true
  LongMethod:
    active: true
    threshold: 80
  LargeClass:
    active: true
    threshold: 300

style:
  active: true
  MagicNumber:
    active: true
    ignoreNumbers: ['-1', '0', '1', '2']
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: true
    ignoreLocalVariableDeclaration: true
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: true
    ignoreNamedArgument: true
    ignoreEnums: true
